// frontend-angular/src/app/components/traje-list/traje-list.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, ActivatedRoute } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { TrajeService } from '../../services/product.service';
import { Traje, MaterialInfo } from '../../models/interfaces';

@Component({
  selector: 'app-traje-list',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  template: `
    <div class="d-flex justify-content-between align-items-center mb-4">
      <h2>
        <i class="fas fa-tshirt me-2"></i>
        Trajes Disponibles
        <span class="badge bg-primary ms-2" *ngIf="filteredTrajes.length > 0">
          {{ filteredTrajes.length }}
        </span>
      </h2>
      <a routerLink="/trajes/add" class="btn btn-fallero">
        <i class="fas fa-plus me-2"></i>
        Nuevo Traje
      </a>
    </div>

    <!-- Filtros -->
    <div class="card mb-4">
      <div class="card-header">
        <h5 class="mb-0">
          <i class="fas fa-filter me-2"></i>
          Filtros
        </h5>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-4">
            <label class="form-label">Buscar por nombre</label>
            <input type="text" 
                   class="form-control" 
                   [(ngModel)]="searchTerm"
                   (input)="applyFilters()"
                   placeholder="Escribir para buscar...">
          </div>
          <div class="col-md-4">
            <label class="form-label">Material</label>
            <select class="form-select" 
                    [(ngModel)]="selectedMaterial"
                    (change)="applyFilters()">
              <option value="">Todos los materiales</option>
              <option *ngFor="let material of materiales" [value]="material.key">
                {{ material.label }}
              </option>
            </select>
          </div>
          <div class="col-md-4">
            <label class="form-label">Propietario</label>
            <input type="text" 
                   class="form-control" 
                   [(ngModel)]="searchPropietario"
                   (input)="applyFilters()"
                   placeholder="Buscar por propietario...">
          </div>
        </div>
        <div class="mt-3">
          <button class="btn btn-outline-secondary" (click)="clearFilters()">
            <i class="fas fa-times me-2"></i>
            Limpiar Filtros
          </button>
        </div>
      </div>
    </div>

    <!-- Lista de trajes -->
    <div class="row" *ngIf="filteredTrajes.length > 0">
      <div class="col-md-6 col-lg-4 col-xl-3 mb-4" *ngFor="let traje of filteredTrajes">
        <div class="card traje-card h-100">
          <div class="position-relative">
            <div class="card-img-top traje-placeholder d-flex flex-column justify-content-center align-items-center"
                 style="height: 200px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);">
              <i class="fas fa-tshirt fa-3x text-white mb-2"></i>
              <small class="text-white">{{ traje.nombre }}</small>
            </div>
            <span class="badge position-absolute top-0 end-0 m-2"
                  [ngClass]="'bg-' + getMaterialColor(traje.material)">
              {{ getMaterialLabel(traje.material) }}
            </span>
          </div>
          
          <div class="card-body d-flex flex-column">
            <h6 class="card-title">{{ traje.nombre }}</h6>
            <p class="card-text text-muted small flex-grow-1">
              <strong>Material:</strong> {{ getMaterialLabel(traje.material) }}<br>
              <strong>Propietario:</strong> {{ traje.propietario }}
            </p>
            
            <div class="mt-auto">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <small class="text-muted" *ngIf="traje.createdAt">
                  <i class="fas fa-calendar me-1"></i>
                  {{ formatDate(traje.createdAt) }}
                </small>
                <small class="text-muted" *ngIf="traje.updatedAt && traje.updatedAt !== traje.createdAt">
                  <i class="fas fa-edit me-1"></i>
                  {{ formatDate(traje.updatedAt) }}
                </small>
              </div>
              
              <div class="d-flex gap-2">
                <a [routerLink]="['/trajes', traje._id]" 
                   class="btn btn-primary btn-sm flex-fill">
                  <i class="fas fa-eye me-1"></i>
                  Ver Detalles
                </a>
                <a [routerLink]="['/trajes/edit', traje._id]" 
                   class="btn btn-outline-warning btn-sm">
                  <i class="fas fa-edit"></i>
                </a>
                <button class="btn btn-outline-danger btn-sm" 
                        (click)="deleteTraje(traje)">
                  <i class="fas fa-trash"></i>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Estado de carga -->
    <div class="text-center" *ngIf="loading">
      <div class="loading-spinner">
        <div class="spinner-border text-primary" role="status">
          <span class="visually-hidden">Cargando trajes...</span>
        </div>
      </div>
    </div>

    <!-- Sin resultados -->
    <div class="text-center py-5" *ngIf="!loading && filteredTrajes.length === 0">
      <i class="fas fa-search fa-3x text-muted mb-3"></i>
      <h4 class="text-muted">No se encontraron trajes</h4>
      <p class="text-muted mb-4">
        Intenta ajustar los filtros o 
        <a routerLink="/trajes/add" class="text-decoration-none">
          crear el primer traje
        </a>
      </p>
    </div>
  `,
  styles: [`
    .btn-fallero {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      border: none;
      color: white;
    }
    
    .btn-fallero:hover {
      background: linear-gradient(135deg, #5a6fd8 0%, #6a4190 100%);
      color: white;
    }
    
    .traje-card {
      transition: transform 0.2s, box-shadow 0.2s;
      border: none;
      box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    }
    
    .traje-card:hover {
      transform: translateY(-5px);
      box-shadow: 0 4px 15px rgba(0,0,0,0.15);
    }
    
    .traje-placeholder {
      border-radius: 0.375rem 0.375rem 0 0;
    }
    
    .loading-spinner {
      padding: 3rem;
    }
    
    @media (max-width: 768px) {
      .d-flex.justify-content-between {
        flex-direction: column;
        gap: 1rem;
      }
    }
  `]
})
export class TrajeListComponent implements OnInit {
  trajes: Traje[] = [];
  filteredTrajes: Traje[] = [];
  materiales: MaterialInfo[] = [];
  loading = true;

  // Filtros
  searchTerm = '';
  selectedMaterial = '';
  searchPropietario = '';

  constructor(
    private trajeService: TrajeService,
    private route: ActivatedRoute
  ) {}

  ngOnInit(): void {
    this.loadMateriales();
    this.loadTrajes();
    this.checkQueryParams();
  }

  loadMateriales(): void {
    this.materiales = this.trajeService.getMateriales();
  }

  checkQueryParams(): void {
    this.route.queryParams.subscribe(params => {
      if (params['material']) {
        this.selectedMaterial = params['material'];
        this.applyFilters();
      }
    });
  }

  loadTrajes(): void {
    this.loading = true;
    this.trajeService.getAllTrajes().subscribe({
      next: (trajes) => {
        this.trajes = trajes;
        this.applyFilters();
        this.loading = false;
      },
      error: (error) => {
        console.error('Error loading trajes:', error);
        this.loading = false;
      }
    });
  }

  applyFilters(): void {
    this.filteredTrajes = this.trajes.filter(traje => {
      // Filtro por término de búsqueda
      const matchesSearch = !this.searchTerm || 
        traje.nombre.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
        traje.material.toLowerCase().includes(this.searchTerm.toLowerCase()) ||
        traje.propietario.toLowerCase().includes(this.searchTerm.toLowerCase());

      // Filtro por material
      const matchesMaterial = !this.selectedMaterial || 
        traje.material.toLowerCase().includes(this.selectedMaterial.toLowerCase());

      // Filtro por propietario
      const matchesPropietario = !this.searchPropietario || 
        traje.propietario.toLowerCase().includes(this.searchPropietario.toLowerCase());

      return matchesSearch && matchesMaterial && matchesPropietario;
    });
  }

  clearFilters(): void {
    this.searchTerm = '';
    this.selectedMaterial = '';
    this.searchPropietario = '';
    this.applyFilters();
  }

  getMaterialLabel(material: string): string {
    const mat = this.materiales.find(m => m.key === material.toLowerCase());
    return mat ? mat.label : material;
  }

  getMaterialColor(material: string): string {
    const mat = this.materiales.find(m => m.key === material.toLowerCase());
    return mat ? mat.color : 'secondary';
  }

  formatDate(dateString: string): string {
    const date = new Date(dateString);
    return date.toLocaleDateString('es-ES', { 
      year: 'numeric', 
      month: 'short', 
      day: 'numeric' 
    });
  }

  deleteTraje(traje: Traje): void {
    if (confirm(`¿Estás seguro de que quieres eliminar el traje "${traje.nombre}"?`)) {
      this.trajeService.deleteTraje(traje._id!).subscribe({
        next: (success) => {
          if (success) {
            this.loadTrajes(); // Recargar la lista
            alert('Traje eliminado correctamente');
          } else {
            alert('Error al eliminar el traje');
          }
        },
        error: (error) => {
          console.error('Error deleting traje:', error);
          alert('Error al eliminar el traje');
        }
      });
    }
  }
}

// frontend-react/src/components/TrajeList.js
import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import { useTrajes } from '../hooks/useTrajes';

const TrajeList = () => {
  const { trajes, loading, error, deleteTraje } = useTrajes();
  const [searchTerm, setSearchTerm] = useState('');

  const filteredTrajes = trajes.filter(traje => 
    traje.nombre.toLowerCase().includes(searchTerm.toLowerCase()) ||
    traje.material.toLowerCase().includes(searchTerm.toLowerCase()) ||
    traje.propietario.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleDelete = async (id, nombre) => {
    if (window.confirm(`¿Estás seguro de que quieres eliminar el traje "${nombre}"?`)) {
      try {
        await deleteTraje(id);
      } catch (error) {
        alert(`Error al eliminar el traje: ${error.message}`);
      }
    }
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('es-ES', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  if (loading) {
    return (
      <div className="text-center py-5">
        <div className="spinner-border text-primary" role="status">
          <span className="visually-hidden">Cargando...</span>
        </div>
        <p className="mt-2">Cargando trajes...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="alert alert-danger" role="alert">
        <h4 className="alert-heading">Error</h4>
        <p>No se pudieron cargar los trajes: {error}</p>
      </div>
    );
  }

  return (
    <div>
      {/* Cabecera */}
      <div className="d-flex justify-content-between align-items-center mb-4">
        <div>
          <h2><i className="fas fa-crown me-2 text-warning"></i>Trajes Falleros</h2>
          <p className="text-muted">Total: {filteredTrajes.length} trajes</p>
        </div>
        <Link to="/trajes/add" className="btn btn-primary">
          <i className="fas fa-plus me-2"></i>Agregar Traje
        </Link>
      </div>

      {/* Buscador */}
      <div className="row mb-4">
        <div className="col-md-6">
          <div className="input-group">
            <span className="input-group-text">
              <i className="fas fa-search"></i>
            </span>
            <input
              type="text"
              className="form-control"
              placeholder="Buscar por nombre, material o propietario..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
        </div>
      </div>

      {/* Lista de trajes */}
      {filteredTrajes.length === 0 ? (
        <div className="text-center py-5">
          <i className="fas fa-tshirt" style={{ fontSize: '80px', color: '#ddd' }}></i>
          <h4 className="mt-3 text-muted">No hay trajes disponibles</h4>
          <p>¡Añade tu primer traje fallero!</p>
          <Link to="/trajes/add" className="btn btn-primary">
            <i className="fas fa-plus me-2"></i>Agregar Traje
          </Link>
        </div>
      ) : (
        <div className="row">
          {filteredTrajes.map((traje) => (
            <div key={traje._id} className="col-lg-6 mb-4">
              <div className="card h-100 shadow-sm border-0">
                <div className="card-body">
                  <div className="d-flex justify-content-between align-items-start mb-3">
                    <h5 className="card-title text-primary fw-bold">
                      <i className="fas fa-tshirt me-2"></i>
                      {traje.nombre}
                    </h5>
                    <div className="dropdown">
                      <button className="btn btn-outline-secondary btn-sm dropdown-toggle" 
                              type="button" 
                              data-bs-toggle="dropdown">
                        <i className="fas fa-ellipsis-v"></i>
                      </button>
                      <ul className="dropdown-menu">
                        <li>
                          <Link to={`/trajes/${traje._id}`} className="dropdown-item">
                            <i className="fas fa-eye me-2"></i>Ver detalles
                          </Link>
                        </li>
                        <li>
                          <Link to={`/trajes/edit/${traje._id}`} className="dropdown-item">
                            <i className="fas fa-edit me-2"></i>Editar
                          </Link>
                        </li>
                        <li><hr className="dropdown-divider" /></li>
                        <li>
                          <button 
                            className="dropdown-item text-danger" 
                            onClick={() => handleDelete(traje._id, traje.nombre)}
                          >
                            <i className="fas fa-trash me-2"></i>Eliminar
                          </button>
                        </li>
                      </ul>
                    </div>
                  </div>

                  <div className="row mb-3">
                    <div className="col-sm-6">
                      <small className="text-muted">Material:</small>
                      <p className="mb-2">
                        <span className="badge bg-info text-dark">
                          <i className="fas fa-fabric me-1"></i>
                          {traje.material}
                        </span>
                      </p>
                    </div>
                    <div className="col-sm-6">
                      <small className="text-muted">Propietario:</small>
                      <p className="mb-2">
                        <span className="badge bg-success">
                          <i className="fas fa-user me-1"></i>
                          {traje.propietario}
                        </span>
                      </p>
                    </div>
                  </div>

                  <div className="text-muted small">
                    <div className="d-flex justify-content-between">
                      <span>
                        <i className="fas fa-calendar-plus me-1"></i>
                        Creado: {formatDate(traje.createdAt)}
                      </span>
                      {traje.updatedAt !== traje.createdAt && (
                        <span>
                          <i className="fas fa-edit me-1"></i>
                          Actualizado: {formatDate(traje.updatedAt)}
                        </span>
                      )}
                    </div>
                  </div>
                </div>
                <div className="card-footer bg-transparent">
                  <div className="d-flex gap-2">
                    <Link to={`/trajes/${traje._id}`} className="btn btn-outline-primary btn-sm flex-grow-1">
                      <i className="fas fa-eye me-1"></i>Ver
                    </Link>
                    <Link to={`/trajes/edit/${traje._id}`} className="btn btn-outline-warning btn-sm flex-grow-1">
                      <i className="fas fa-edit me-1"></i>Editar
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default TrajeList;
